STORE_CRED_KEY = "creds"
STORE_PROJECT_KEY = "project_data"
STORE_PROJECT_META_KEY = "project_meta"
STORE_ENTITIES = {STORE_CRED_KEY, STORE_PROJECT_KEY, STORE_PROJECT_META_KEY}
SAFA_AUTH_TOKEN = 'SAFA-TOKEN'
